version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "lambda-dynamodb"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-2qb11syrhw3k"
s3_prefix = "lambda-dynamodb"
region = "us-east-2"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
disable_rollback = true
image_repositories = []
