name: 'RESTAPI: DynamoDB/Lambda/API Gateway'

# **What it does**: Renders the content of every page and check all internal links.
# **Why we have it**: To make sure all links connect correctly.
# **Who does it impact**: Docs content. 

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
      
permissions:
  contents: read
  # Needed for the 'trilom/file-changes-action' action
  pull-requests: read

# This allows a subsequently queued workflow run to interrupt previous runs
concurrency:
  group: '${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}'
  cancel-in-progress: true

jobs:
  build:
    runs-on: ${{ fromJSON('["ubuntu-latest", "self-hosted"]')[github.repository == 'github/docs-internal'] }}
    defaults:
       run:
         working-directory: ./rest
    strategy: 
      matrix:
        node-version: [14.x] 
    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2
      - name: Run CodeBuild
        uses: aws-actions/aws-codebuild-run-build@v1
        with:
          project-name: CodeBuildProjectName
          
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup node.js [${{ matrix.node-version }}]
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: npm
          cache-dependency-path: '**/package-lock.json'

      - name: Install
        run: npm ci        
        
      - name: Build
        run: npm build --if-present

      - name: Test
        run: npm test        
        
